# Generated by Django 3.2.20 on 2023-10-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20231003_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.book')),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, through='student.Borrow', to='student.Book'),
        ),
    ]
