# Generated by Django 3.2.20 on 2023-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
