# Generated by Django 3.2.20 on 2023-10-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20231007_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
